---
- hosts: localhost
  gather_facts: no
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install docker and some dependencies
      yum:
        name: python2-pip
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Install docker python module
      pip:
        name: docker
        executable: pip

    - name: Start docker container
      docker_container:
        name: eureka
        image: 661413504645.dkr.ecr.us-east-2.amazonaws.com/specsavers:latest
        state: started
        recreate: yes
        ports:
          - 8761:8761
