version: '3'
services:
  nginx:
   container_name: some-nginx
   build: ./nginx
   restart: always
   ports:
   - 8081:80
   depends_on:
   - eureka
   networks:
   - frontend

  eureka:
   restart: always
   build: ./eureka
   expose:
   - "8761"
   networks:
   - frontend

networks:
  frontend:
    driver: bridge
